version: '3.1'
services:
  redis:
    image: redis:5
    restart: "no"
    ports:
     - "6379:6379"

  mongo:
    image: mongo:3.6
    restart: "no"
    network_mode: host
    entrypoint:
      - /usr/bin/mongod
      - --bind_ip_all
      - --replSet
      - testReplSet

  setupMongo:
    image: mongo:3.6
    restart: "no"
    network_mode: host
    depends_on:
      - mongo
    entrypoint:
      - bash
      - -c
      - "sleep 10 && mongo --host mongodb://localhost:27017 --eval 'rs.initiate({_id:\"testReplSet\",members:[{_id:0,host:\"localhost:27017\"}]})'"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: "no"
    ports:
      - 5672:5672
      - 15672:15672

