version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
  upload-coverage-report:
    steps:
      - run:
          command: curl -XGET 'https://codecov.io/bash' | bash

jobs:
  fmt-check:
    parameters:
      nodeVersionTag:
        type: string

    executor:
      name: node/default
      tag: <<parameters.nodeVersionTag>>

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run fmt:check

  all-tests:
    parameters:
      node-version:
        type: string

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - node/install:
          node-version: <<parameters.node-version>>
      - node/install-packages
      - run:
          command: npm run deps:detached && sleep 10
      - run:
          command: npm run test:coverage-report
      - upload-coverage-report

workflows:
  required-checks:
    jobs:
      - fmt-check:
          name: fmt-check
          node-version: "12.18.0"

      - all-tests:
          name: tests-node-12
          node-version: "12.18.0"

  optional-checks:
    jobs:
      - all-tests:
          name: tests-node-lts
          node-version: lts

