version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
  setup-package:
    steps:
      - checkout
      - node/install-packages

  upload-coverage-report:
    steps:
      - run:
          command: curl -XGET 'https://codecov.io/bash' | bash

jobs:
  fmt-check:
    parameters:
      nodeVersionTag:
        type: string

    executor:
      name: node/default
      tag: <<parameters.nodeVersionTag>>

    steps:
      - setup-package
      - run:
          command: npm run fmt:check

  all-tests:
    parameters:
      nodeVersionTag:
        type: string

    executor:
      name: node/default
      tag: <<parameters.nodeVersionTag>>

    steps:
      - setup-package
      - run:
          command: npm run deps:detached && sleep 10
      - run:
          command: npm run test:coverage-report
      - upload-coverage-report

workflows:
  required-checks:
    jobs:
      - fmt-check:
          name: fmt-check
          nodeVersionTag: "12.18"

      - all-tests:
          name: tests-node-12
          nodeVersionTag: "12.18"

  optional-checks:
    jobs:
      - all-tests:
          name: tests-node-lts
          nodeVersionTag: lts

