version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
  upload-coverage-report:
    steps:
      - run:
          command: curl -XGET 'https://codecov.io/bash' | bash

jobs:
  fmt-check:
    parameters:
      node-version-tag:
        type: string

    executor:
      name: node/default
      tag: <<parameters.node-version-tag>>

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run fmt:check

  all-tests:
    parameters:
      node-version:
        type: string

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          command: nvm install "<<parameters.node-version>>"
      - run:
          command: nvm use "<<parameters.node-version>>"
      - node/install-packages
      - run:
          command: npm run deps:detached && sleep 10
      - run:
          command: npm t
      - run:
          command: npm run test:coverage-report
      - upload-coverage-report

workflows:
  required-checks:
    jobs:
      - fmt-check:
          name: fmt-check
          node-version-tag: "12.18"

      - all-tests:
          name: tests-node-12
          node-version: "12.18.0"

  # FIXME "nvm install lts/*" works locally but does not work on CircleCI
  optional-checks:
    jobs:
      - all-tests:
          name: tests-node-14
          node-version: "14"

